% paramSet_volley.m
% Parameter setting GUI
% Programmed by AKito Kosugi
%
% v.4.0        08.19.2022    added "Recording location" section
% v.3.1        06.14.2022    Bag fixed
% v.3.0        03.28.2022    
% v.2.1.2      03.21.2022    added "stimIntensity_mw"
% v.2.1.1      03.10.2022    Bag fixed
% v.2.1        03.01.2022    added "Stimulation parameter" section
% v.2.0.1      01.19.2022    added "Save" section
% v.2.0        12.24.2021
% v.1.0.2      12.21.2015    Bag fixed
% v..1.0.1     12.18.2015    Bag fixed
% v..1.0       12.16.2015

close all
clc


%% Initialization

screenSize = get(0,'screensize');
uiIndex = 1;

stimType_all = {'elect', 'opt_S','opt_L','opt_doric_c','opt_doric_g','opt_doric_y','opt_doric_o'};
analysisType_all = {'order','intensity','duration','depth'};

param_volley_ui1.recChannel = 0;
param_volley_ui2.dataNum = 1;
param_volley_ui2.recFs = 50000;
param_volley_ui2.recGain = 1;
param_volley_ui2.stimIdx = 1;
param_volley_ui2.stimType = char(stimType_all(param_volley_ui2.stimIdx));
param_volley_ui2.stimDelay = 10;
param_volley_ui2.stimDuration = 0.1;
param_volley_ui2.stimIntensity = 1;
param_volley_ui2.laterality = 0;
param_volley_ui2.depth = 0;
param_volley_ui3.analysisIdx = 1;
param_volley_ui3.analysisType = char(analysisType_all(param_volley_ui3.analysisIdx));
param_volley_ui3.plotIdx = num2str([1 2 3 4 5]);
param_volley_ui3.plotYlim = num2str([-1 1]);


%% Set GUI 1

%---GUI 1: Select analysis step---%
h = figure(100);
set(h,'position',[screenSize(1)+screenSize(3)*2/10 screenSize(2)+screenSize(4)*2/10 screenSize(3)*3/10 screenSize(4)*6/10]);
set(gcf,'name','Volley analysis')

ui1 =uibuttongroup(h,'title','Analysis',...
            'unit','normalize',...
            'position',[0.05 0.3 0.5 0.62],...
            'fontsize',25,...
            'fontweight','bold');    

ui1_1 = uicontrol(ui1,'style','radiobutton',...
            'unit','normalize',...
            'position',[0.1 0.8 0.8 0.1],...
            'string','1. Convert abf file',...
            'fontsize',15,...
            'fontweight','bold',...
            'callback', 'uiIndex = 1;');

        
ui1_2=uicontrol(ui1,'style','radiobutton',...
            'unit','normalize',...
            'position',[0.1 0.6 0.8 0.1],...
            'string','2. Check sweep',...
            'fontsize',15,...
            'fontweight','bold',...
            'callback', 'uiIndex = 2;');        
                        
ui1_3=uicontrol(ui1,'style','radiobutton',...
            'unit','normalize',...
            'position',[0.1 0.4 0.8 0.1],...
            'string','3. Analyze I/O curve',...
            'fontsize',15,...
            'fontweight','bold',...
            'callback', 'uiIndex = 3;');             

ui1_3=uicontrol(ui1,'style','radiobutton',...
            'unit','normalize',...
            'position',[0.1 0.2 0.8 0.1],...
            'string','4. Compare between subjects',...
            'fontsize',15,...
            'fontweight','bold',...
            'callback', 'uiIndex = 4;');          
        
uicontrol(h,'style','push',...
            'unit','normalize',...
            'position',[0.78 0.11 0.2 0.1],...
            'string','OK',...
            'fontsize',25,...
            'fontweight','bold',...
            'callback','close(100);');    
                
uiwait

switch uiIndex
    case 1
        if exist('param_volley_ui1.mat','file') > 0
            load('param_volley_ui1.mat')
        end
    case 2
        if exist('param_volley_ui2.mat','file') > 0
            load('param_volley_ui2.mat')
        end
    case 3
        if exist('param_volley_ui3.mat','file') > 0
            load('param_volley_ui3.mat')
        end        
end


%% Set GUI 2

%---GUI 2: Input experiment parameters---%       
switch uiIndex
    case 1
        h = figure(200);
        set(h,'position',[screenSize(1)+screenSize(3)*2/10 screenSize(2)+screenSize(4)*2/10 screenSize(3)*3/10 screenSize(4)*6/10]);
        set(gcf,'name','Input parameters')
        
        ui2 =uibuttongroup(h,'title','Recording parameter',...
            'unit','normalize',...
            'position',[0.05 0.3 0.5 0.62],...
            'fontsize',25,...
            'fontweight','bold');    
        
        uicontrol(ui2,'style','text',...
                'unit','normalize',...
                'position',[0.05 0.8 0.6 0.15],...
                'string','input channel (IN)',...
                'fontsize',15,...
                'fontweight','bold');        
        ui2_1 = uicontrol(ui2,'style','edit',...
                    'unit','normalize',...
                    'position',[0.75 0.9 0.2 0.05],...
                    'string',num2str(param_volley_ui1.recChannel),...
                    'HorizontalAlignment','left'); 
            
        uicontrol(h,'style','push',...
            'unit','normalize',...
            'position',[0.78 0.11 0.2 0.1],...
            'string','OK',...
            'fontsize',25,...
            'fontweight','bold',...
            'callback','recChannel = str2num(get(ui2_1,''string''));close(200);');
        uiwait
        
    case 2
        h = figure(200);
        set(h,'position',[screenSize(1)+screenSize(3)*2/10 screenSize(2)+screenSize(4)*2/10 screenSize(3)*6/10 screenSize(4)*6/10]);
        set(gcf,'name','Input parameters')
 
        %---Left panel: reacording parameters---%
        ui2 =uibuttongroup(h,'title','Recording parameters',...
            'unit','normalize',...
            'position',[0.05 0.3 0.27 0.62],...
            'fontsize',25,...
            'fontweight','bold');    
        
        uicontrol(ui2,'style','text',...
                'unit','normalize',...
                'position',[0.05 0.8 0.6 0.15],...
                'string','File number',...
                'fontsize',15,...
                'fontweight','bold');        

        ui2_1 = uicontrol(ui2,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.9 0.2 0.05],...
                            'string',num2str(param_volley_ui2.dataNum),...
                            'HorizontalAlignment','left'); 

        uicontrol(ui2,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.65 0.6 0.15],...
                    'string','Sampling rate [Hz] ',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui2_2 = uicontrol(ui2,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.75 0.2 0.05],...
                            'string',num2str(param_volley_ui2.recFs),...
                            'HorizontalAlignment','left');                 

        uicontrol(ui2,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.5 0.6 0.15],...
                    'string','Pre amilifier gain [mV/V]',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui2_3 = uicontrol(ui2,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.6 0.2 0.05],...
                            'string',num2str(param_volley_ui2.recGain),...
                            'HorizontalAlignment','left');  

        %---Center panel: Stimulation parameters---% 
        ui3 =uibuttongroup(h,'title','Stimulation parameters',...
                    'unit','normalize',...
                    'position',[0.37 0.3 0.27 0.62],...
                    'fontsize',25,...
                    'fontweight','bold'); 

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.8 0.6 0.15],...
                    'string','Type',...
                    'fontsize',15,...
                    'fontweight','bold');       

        ui3_1 = uicontrol(ui3,'style','popupmenu',...
                            'unit','normalize',...
                            'position',[0.75 0.9 0.2 0.05],...
                            'HorizontalAlignment','left',...
                            'string',stimType_all,...
                            'value',param_volley_ui2.stimIdx);

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.65 0.6 0.15],...
                    'string','Delay [ms]',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui3_2 = uicontrol(ui3,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.75 0.2 0.05],...
                            'string',num2str(param_volley_ui2.stimDelay),...
                            'HorizontalAlignment','left');                 

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.5 0.6 0.15],...
                    'string','Duration [ms]',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui3_3 = uicontrol(ui3,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.6 0.2 0.05],...
                            'string',num2str(param_volley_ui2.stimDuration),...
                            'HorizontalAlignment','left');  

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.02 0.35 0.7 0.15],...
                    'string','Intensity (mA or %)',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui3_4 = uicontrol(ui3,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.45 0.2 0.05],...
                            'string',num2str(param_volley_ui2.stimIntensity),...
                            'HorizontalAlignment','left');                              

        %---Left panel: Recording location---% 
        ui4 =uibuttongroup(h,'title','Recording location',...
                    'unit','normalize',...
                    'position',[0.69 0.3 0.27 0.62],...
                    'fontsize',25,...
                    'fontweight','bold'); 

        uicontrol(ui4,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.8 0.6 0.15],...
                    'string','Laterality [É m]',...
                    'fontsize',15,...
                    'fontweight','bold');       

        ui4_1 = uicontrol(ui4,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.9 0.2 0.05],...
                            'HorizontalAlignment','left',...
                            'string',param_volley_ui2.laterality);

        uicontrol(ui4,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.65 0.6 0.15],...
                    'string','Depth [É m]',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui4_2 = uicontrol(ui4,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.75 0.2 0.05],...
                            'string',param_volley_ui2.depth,...
                            'HorizontalAlignment','left');                 
                        
        uicontrol(h,'style','push',...
                'unit','normalize',...
                'position',[0.78 0.11 0.2 0.1],...
                'string','OK',...
                'fontsize',25,...
                'fontweight','bold',...
                'callback','dataNum = str2num(get(ui2_1,''string'')); recFs = str2num(get(ui2_2,''string'')); recGain = str2num(get(ui2_3,''string''));stimIdx = get(ui3_1,''value'');stimType = char(stimType_all(stimIdx));stimDelay = str2num(get(ui3_2,''string''));stimDuration = str2num(get(ui3_3,''string''));stimIntensity = str2num(get(ui3_4,''string''));laterality = str2num(get(ui4_1,''string''));depth = str2num(get(ui4_2,''string''));close(200);');    

        uiwait

        %---Convert optical stimulation intensity---%
        switch stimType
            case 'opt_S'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
            case 'opt_L'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
            case 'opt_doric_c'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
            case 'opt_doric_g'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
            case 'opt_doric_y'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
            case 'opt_doric_o'
                stimIntensity_mw = stimIntConv(stimIntensity,stimType);
        end
        
    case 3
        h = figure(200);
        set(h,'position',[screenSize(1)+screenSize(3)*2/10 screenSize(2)+screenSize(4)*2/10 screenSize(3)*6/10 screenSize(4)*6/10]);
        set(gcf,'name','Input parameters')
 
        %---Left panel: reacording parameters---%
        ui3 =uibuttongroup(h,'title','Analysis parameters',...
            'unit','normalize',...
            'position',[0.05 0.3 0.27 0.62],...
            'fontsize',25,...
            'fontweight','bold');    
        
        uicontrol(ui3,'style','text',...
                'unit','normalize',...
                'position',[0.05 0.8 0.6 0.15],...
                'string','Input parameter',...
                'fontsize',15,...
                'fontweight','bold');       
                        
        ui3_1 = uicontrol(ui3,'style','popupmenu',...
                            'unit','normalize',...
                            'position',[0.65 0.9 0.3 0.05],...
                            'HorizontalAlignment','left',...
                            'string',analysisType_all,...
                            'value',param_volley_ui3.analysisIdx);                        

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.65 0.6 0.15],...
                    'string','Plot data index',...
                    'fontsize',15,...
                    'fontweight','bold');                            
                        
        ui3_2 = uicontrol(ui3,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.75 0.2 0.05],...
                            'string',param_volley_ui3.plotIdx,...
                            'HorizontalAlignment','left');                 

        uicontrol(ui3,'style','text',...
                    'unit','normalize',...
                    'position',[0.05 0.5 0.6 0.15],...
                    'string','Plot scale Y-axis [mV]',...
                    'fontsize',15,...
                    'fontweight','bold');        

        ui3_3 = uicontrol(ui3,'style','edit',...
                            'unit','normalize',...
                            'position',[0.75 0.6 0.2 0.05],...
                            'string',param_volley_ui3.plotYlim,...
                            'HorizontalAlignment','left');                          
                        
         uicontrol(h,'style','push',...
                     'unit','normalize',...
                     'position',[0.78 0.11 0.2 0.1],...
                     'string','OK',...
                     'fontsize',25,...
                     'fontweight','bold',...
                     'callback','analysisIdx = get(ui3_1,''value'');analysisType = char(analysisType_all(analysisIdx)); plotIdx = str2num(get(ui3_2,''string'')); plotYlim = str2num(get(ui3_3,''string''));close(200);');    
         uiwait                      
end


%% Save

switch uiIndex
    case 1
        param_volley_ui1.recChannel = recChannel;
        save('param_volley_ui1.mat','param_volley_ui1');
    case 2
        param_volley_ui2.dataNum = dataNum;
        param_volley_ui2.recFs = recFs;
        param_volley_ui2.recGain = recGain;
        param_volley_ui2.stimIdx = stimIdx;
        param_volley_ui2.stimType = stimType;
        param_volley_ui2.stimDelay = stimDelay;
        param_volley_ui2.stimDuration = stimDuration;
        param_volley_ui2.stimIntensity = stimIntensity;
        param_volley_ui2.laterality = laterality;
        param_volley_ui2.depth = depth;
        if exist('stimIntensity_mw') == 1
            param_volley_ui2.stimIntensity_mw = stimIntensity_mw;
        end
        save('param_volley_ui2.mat','param_volley_ui2');
    case 3
        param_volley_ui3.analysisIdx = analysisIdx;
        param_volley_ui3.analysisType = analysisType;
        param_volley_ui3.plotIdx = num2str(plotIdx);
        param_volley_ui3.plotYlim = num2str(plotYlim);
        save('param_volley_ui3.mat','param_volley_ui3');        
end