function [] = savePanel(saveData)
%savePanel データの保存に使用するGUI
%   V.2.0 03.29.2022
%   V.1.0 12.16.2015
    
    screenSize = get(0,'screensize');

    h = figure(100);
    set(h,'position',[screenSize(1)+screenSize(3)*6/10 screenSize(2)+screenSize(4)*1/10 screenSize(3)*2/10 screenSize(4)*2/10]);
    set(h,'name','Save panel')
    uicontrol(h,'Style','pushbutton',...
        'String','Save file',...
        'FontSize',20,...
        'unit','normalize',...
        'Position',[0.2 0.6 0.5 0.2],...
        'Callback',['[fileName pathName] = uiputfile(''.mat'');'...  
                    'correntDir = pwd;'...        
                    'cd(pathName);'...       
                    'save(fileName,''saveData'');'...
                    'close gcf;'...
                    'figHandles =  findobj(''type'',''figure'');'...
                    'figNum = length(figHandles);'...
                    'for i = 1:1:figNum;'...
                    'saveas(figHandles(i),[fileName(1:end-4) ''_'' num2str(figNum-i+1) ''.fig'']);'...
                    'saveas(figHandles(i),[fileName(1:end-4) ''_'' num2str(figNum-i+1) ''.bmp'']);'...
                    'pause(1);',...
                    'close gcf;end;',...
                    'cd(correntDir);close all;']);
     uicontrol(h,'Style','pushbutton',...
            'String','Close all',...
            'FontSize',20,...
            'unit','normalize',...
            'Position',[0.2 0.2 0.5 0.2],...
            'Callback','close all');

end

